testcafe tests
cdroulers/block-fly pull request #33
Opened 2017-02-03 11:33 UTC by miherlosev

2017-02-03 16:34 UTC, cdroulers requested changes
If have minor changes I put as comments.

Also, use 2 spaces instead of 4 and an lf at the end of the file (to respect `.editorconfig` settings)

Then I'll be happy to merge!

I can also merge in another branch and to that myself!

2017-02-03 16:34 UTC, cdroulers commented on test/e2e/index-test.js
> +import IndexPage from './page-model';
Rename to "main.password.spec.js" to follow convention for other tests.

main.{fixture}.spec.js for all tests, to separate concerns.

2017-02-03 16:34 UTC, cdroulers commented on test/e2e/page-model.js
> +import { Selector } from 'testcafe';
Rename to `IndexPage.js` and move to a `pages` folder as well.

2017-02-03 16:45 UTC, cdroulers commented
Wow! That was quick and easy! I'm impressed with how easy that was!

I had used the closed source testcafé before and thought it was ok, but this is pretty amazing!

I just installed nightmare and the plugin to test it and the test fails with 

```
× enter password

   1) A call to an async function is not awaited. Use the "await" keyword before actions, assertions or chains of them to ensure
      that they run in the right sequence.

      Browser: Electron 1.4.15 / Windows 10 0.0.0

         14 |        .typeText(indexPage.dialogs.enterPassword.password, 'wrong')
         15 |        .click(indexPage.dialogs.enterPassword.submit)
         16 |        .expect(indexPage.messageBar.text.textContent).contains("Couldn't find a level with password wrong.")
         17 |        .click(indexPage.menu.enterPassword)
         18 |        .click(indexPage.dialogs.enterPassword.cancel)
       > 19 |        .expect(indexPage.dialogs.enterPassword.visible).notOk();
         20 |});
         21 |

         at <anonymous> (C:\dev\cdroulers\block-fly\test\e2e\index-test.js:19:57)
         at step (C:\dev\cdroulers\block-fly\test\e2e\index-test.js:1:612)
         at <anonymous> (C:\dev\cdroulers\block-fly\test\e2e\index-test.js:1:782)
```

I tried to add a debugger statement in the `test('enter password'` but it didn't stop. Any pointers?

2017-02-03 16:47 UTC, cdroulers commented on test/e2e/index-test.js
> +test('enter password', async t => {
Use double-quotes! I forgot about that. I'll setup eslint later.

2017-02-06 08:29 UTC, miherlosev commented
Cann't reproduce the issue with nightmare.
See [vide](https://www.screencast.com/t/JYdJZowcaTM) with my actions.
It looks like nightmare problem as in Google Chrome all works good.

2017-02-06 08:55 UTC, miherlosev commented
You can learn about all features related to debugging in https://github.com/VasilyStrelyaev/testcafe/blob/4d3ca2b7962dae68bf57778417bbdab8a7ca4cc7/docs/articles/documentation/recipes/debugging-tests.md

This article is in progress.
At present, you can use everything this article suggests except for the `t.debug` action - It will be avalible in the next public release.

2017-02-06 15:54 UTC, cdroulers approved these changes

2017-02-06 15:55 UTC, merged

2017-02-10 09:45 UTC, miherlosev commented
Hello @cdroulers.
As I see, you have a good impression about TestCafe.
Could you please tweet about us if it's possible?

2017-02-10 13:49 UTC, cdroulers commented
I can tweet to my 2 followers, but I'll probably blog about it soon!
Thanks for the help